// API Keys Configuration
const CONFIG = {
    WHALE_ALERT_API_KEY: "lkvcIzoP3Kg5L3z5dvHLhe8SgDYX4yIu",
    COINGLASS_API_KEY: "YOUR_COINGLASS_API_KEY_HERE",
    REFRESH_INTERVAL: 60000,
    MINIMUM_BTC_AMOUNT: 10
};